"""
Gemini Service — sends the user's image + style prompt to Google Gemini
and returns the generated image bytes.

Uses the new official `google-genai` SDK (google-generativeai is deprecated).
Model: gemini-2.0-flash-preview-image-generation
  (supports image input + image output in a single call)
"""

import base64
import time
from google import genai
from google.genai import types
from app.core.config import settings


def _get_client() -> genai.Client:
    return genai.Client(api_key=settings.GEMINI_API_KEY)


# Gemini Image Generation candidates prioritized by user request.
# These models support image-to-image transformation via the IMAGE response modality.



def transform_image(
    image_bytes: bytes,
    image_mime: str,
    prompt: str,
    model: str | None = None,
) -> tuple[bytes, float]:
    """
    Send image + prompt to Gemini and return (generated_image_bytes, processing_time_seconds).
    If model is set (e.g. "models/gemini-3-flash-preview"), use only that model; otherwise
    try multiple models in order of capability.
    """
    client = _get_client()
    
    if model:
        candidates = [model]
    else:
        candidates = [
            "models/gemini-2.5-flash-image",
            "models/gemini-3-pro-image-preview",
            "models/gemini-2.0-flash-exp-image-generation",
        ]

    errors = []
    start = time.time()

    for model_name in candidates:
        try:
            print(f"Attempting image generation with model: {model_name}")
            response = client.models.generate_content(
                model=model_name,
                contents=[
                    types.Part.from_text(text=prompt),
                    types.Part.from_bytes(data=image_bytes, mime_type=image_mime),
                ],
                config=types.GenerateContentConfig(
                    response_modalities=["IMAGE"],
                ),
            )
            
            elapsed = round(time.time() - start, 2)

            # Extract the image bytes from the response (API may return base64 or raw bytes)
            if response.candidates and response.candidates[0].content.parts:
                for part in response.candidates[0].content.parts:
                    if part.inline_data and part.inline_data.mime_type and part.inline_data.mime_type.startswith("image/"):
                        print(f"Success with {model_name} in {elapsed}s")
                        data = part.inline_data.data
                        if isinstance(data, bytes):
                            return data, elapsed
                        return base64.b64decode(data), elapsed
            
            error_msg = f"Model {model_name} did not return an image content part."
            print(error_msg)
            errors.append(error_msg)
            
        except Exception as e:
            error_msg = f"{model_name} failed: {str(e)}"
            print(error_msg)
            errors.append(error_msg)
            continue

    # Join all errors to help debugging
    detailed_error = " | ".join(errors)
    raise ValueError(f"AI generation failed for all models. Details: {detailed_error}")


def build_final_prompt(
    prompt_template: str,
    mood: str | None = None,
    weather: str | None = None,
    dress_style: str | None = None,
    custom_prompt: str | None = None,
) -> str:
    """
    Merge the style's base prompt template with the user's optional customisations
    into one final string sent to Gemini.
    """
    parts = [prompt_template]

    if mood:
        parts.append(f"The mood should feel {mood}.")
    if weather:
        parts.append(f"The weather/environment should look {weather}.")
    if dress_style:
        parts.append(f"The subject's clothing style should be {dress_style}.")
    if custom_prompt:
        parts.append(f"Additional instruction: {custom_prompt}")

    parts.append(
        "Maintain the subject's facial features and identity. Output only the transformed image."
    )

    return " ".join(parts)


def calculate_similarity(
    generated_image_bytes: bytes,
    target_image_url: str,
) -> float:
    """
    Use Gemini to compare the generated result with a target reference image.
    Returns a score between 0.0 and 100.0.
    """
    client = _get_client()
    
    # We use a vision model to compare two images
    # We can fetch the target image from URL or just send its URL if Gemini supports it directly,
    # but for reliability we ask Gemini to compare the generated bytes with the target URL's content.
    
    prompt = """
    Compare these two images:
    1. The 'Target' aesthetic we want to match.
    2. The 'Generated' result from a user.

    Evaluate how well the 'Generated' image matches the visual style, lighting, 
    color palette, and artistic mood of the 'Target'. 
    Ignore the actual person/subject identity; focus only on the style and execution.

    Return only a single number between 0 and 100 representing the percentage match.
    Do not include any other text.
    """

    try:
        # Note: In a production environment, you might want to download target_image_url 
        # to bytes first for faster/more reliable multimodal processing.
        # For simplicity, we assume the target_image_url can be accessed or we use its bytes if available.
        
        # For this version, we'll assume the prompt works by describing the target if we don't have its bytes yet
        # or we could fetch the bytes. Let's fetch the bytes since we have target_image_url.
        import requests
        target_response = requests.get(target_image_url, timeout=10)
        target_bytes = target_response.content if target_response.status_code == 200 else None

        if not target_bytes:
            return 0.0

        response = client.models.generate_content(
            model="gemini-2.0-flash", # Use a fast vision model for scoring
            contents=[
                types.Part.from_text(text=prompt),
                types.Part.from_bytes(data=target_bytes, mime_type="image/jpeg"),
                types.Part.from_bytes(data=generated_image_bytes, mime_type="image/jpeg"),
            ],
            config=types.GenerateContentConfig(
                response_mime_type="text/plain",
            ),
        )

        text_score = response.text.strip()
        # Clean up any non-numeric characters just in case
        import re
        numbers = re.findall(r"\d+\.?\d*", text_score)
        if numbers:
            score = float(numbers[0])
            return min(max(score, 0.0), 100.0)
        
        return 0.0
    except Exception as e:
        print(f"Similarity scoring failed: {e}")
        return 0.0
